const Map<String, String> weatherIcons = {
"Mostly Cloudy"
"Mostly Cloudy": "assets/icons/mostly_cloudy.svg",
"Slight Chance Light Snow": "assets/icons/snow_showers.svg",
"Chance Light Snow": "assets/icons/flurries.svg",
"Partly Cloudy": "assets/icons/partly_cloudy.svg",
"Mostly Sunny": "assets/icons/mostly_sunny.svg",
"Sunny": "assets/icons/sunny.svg",
"Mostly Clear": "assets/icons/mostly_clear.svg",
"Heavy Snow Likely": "assets/icons/heavy_snow.svg",
"Heavy Snow": "assets/icons/heavy_snow.svg",
"Partly Sunny" : "assets/icons/sunny.svg",
"Light Snow Likely": "assets/icons/flurries.svg", 
"Snow": "assets/icons/snow_showers.svg",
"Slight Chance Light Rain": "assets/icons/droplet_light.svg",
"Chance Light Rain": "assets/icons/droplet_light.svg",
"Light Rain": "assets/icons/droplet_drizzle.svg",
"Light Snow": "assets/icons/flurries.svg",
"Snow Likely": "assets/icons/snow_showers.svg",
"Patchy Blowing Dust": "assets/icons/dust.svg",
"Slight Chance Rain And Snow": ,
"Chance Rain And Snow" : "assets/icons/wintry_mix.svg",
"Rain And Snow Likely" : "assets/icons/wintry_mix.svg",
"Light Rain Likely": "assets/icons/droplet_light.svg",
"Rain And Snow": "assets/icons/wintry_mix.svg",
"Cloudy": "assets/icons/cloudy.svg",
"Slight Chance Freezing Drizzle": "assets/icons/droplet_light.svg",
"Patchy Fog": "assets/icons/fog.svg",
"Areas Of Fog" : "assets/icons/fog.svg",
"Slight Chance Rain Showers": "assets/icons/droplet_light.svg",
"Chance Rain Showers": "assets/icons/droplet_light.svg",
"Chance Showers And Thunderstorms" : "assets/icons/thunder.svg",
"Showers And Thunderstorms Likely": "assets/icons/strong_tstorms.svg.svg",
"Showers And Thunderstorms": "assets/icons/strong_tstorms.svg",
"Rain Showers": "assets/icons/droplet_light.svg",
"Rain Showers Likely": "assets/icons/droplet_light.svg",
"Slight Chance Showers And Thunderstorms": "assets/icons/thunder.svg",
"Patchy Blowing Snow"  : "assets/icons/blizzard.svg",
"Slight Chance Snow Showers": "assets/icons/snow_showers.svg",
"Clear": "assets/icons/sunny.svg",
"Chance Rain And Snow Showers": "assets/icons/wintry_mix.svg",
"Heavy Snow And Patchy Blowing Snow": "assets/icons/heavy_snow.svg",
"Snow And Patchy Blowing Snow": "assets/icons/snow_showers.svg",
"Chance Sleet": "assets/icons/sleet_hail.svg",
"Chance Freezing Rain": "assets/icons/sleet_hail.svg",
"Freezing Rain": "assets/icons/sleet_hail.svg",
"Chance Snow Showers": "assets/icons/snow_showers.svg",
"Freezing Rain Likely": "assets/icons/sleet_hail.svg",
"Slight Chance Drizzle": "assets/icons/droplet_light.svg",
"Chance Freezing Drizzle": "assets/icons/sleet_hail.svg",
"Freezing Drizzle Likely": "assets/icons/sleet_hail.svg",
"Rain": "assets/icons/droplet_heavy.svg",

};